# Generated by Django 5.1.2 on 2024-11-03 11:10

import posts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.CharField(default=posts.utils.generate_id, max_length=255, primary_key=True, serialize=False)),
                ('comment_email', models.EmailField(max_length=254)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.CharField(default=posts.utils.generate_id, max_length=255, primary_key=True, serialize=False)),
                ('post_email', models.EmailField(max_length=254)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
