# Generated by Django 5.1.2 on 2024-11-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
